db:
  image: mongo:latest
  command: ["mongod", "--smallfiles"]
  volumes:
    - /mongodata:/data/db
  ports:
    - "27017:27017"

api:
  build: ./api
  ports:
    - "8080"
  links:
    - db

lbc:
  image: nginx:alpine
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  ports:
    - "80:80"
  links:
    - api:api
